apiVersion: v1
kind: Service
metadata:
  name: {{ include "patroni-exporter.fullname" . }}
  labels:
    {{- include "patroni-exporter.labels" . | nindent 4 }}
    patroni-monitor: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "patroni-exporter.selectorLabels" . | nindent 4 }}
{{- if .Values.databaseService.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.databaseService.name }}
  labels:
    {{- include "patroni-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.databaseService.type }}
  ports:
    - port: {{ .Values.databaseService.port }}
      targetPort: {{ .Values.databaseService.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- .Values.databaseService.selector | toYaml | nindent 4 }}
{{- end }}